# Generated by Django 5.1.15 on 2026-05-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('alt', models.CharField(blank=True, default='', max_length=150)),
                ('badge', models.CharField(blank=True, default='', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'actions',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AddField(
            model_name='stat',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='icon',
            field=models.CharField(blank=True, default='fa-chart-bar', max_length=50),
        ),
        migrations.AddField(
            model_name='stat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
