# Generated by Django 5.1.15 on 2026-05-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seed_admin_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='alt_ar',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='action',
            name='alt_en',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='action',
            name='badge_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='badge_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='description_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='action',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='action',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='action',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='stat',
            name='description_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stat',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stat',
            name='stat_label_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stat',
            name='stat_label_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
